var API_ADMIN_LOGIN = "http://bkparking.ddns.net:3002/admin_login"
var API_ADMIN_REGISTER = "http://bkparking.ddns.net:3002/admin_register"
var API_PARKINGLOT_INFO = "bkparking.ddns.net/parkinglots"
var API_BOOKING_LIST = "http://bkparking.ddns.net:3002/bookings"
var API_PARKINGLOTS_LIST = "http://bkparking.ddns.net:3002/parkinglots"
var API_USER_LIST = "http://bkparking.ddns.net:3002/users"